### ISSUE TITLE
onDidChangeCurrentKeyboardLayout will never be called

### ISSUE THREAD

**Issue by vadim-ch** [atom/keyboard-layout#35]
Hi there!
In .onDidChangeCurrentKeyboardLayout(callback) callback will never be called.

https://github.com/atom/keyboard-layout/blob/f98a3306a4f7eeb06002dc25a7b8e19d18783f1f/lib/keyboard-layout.js#L42
Here it is written that we are listening to the event "did-change-current-keyboard-layout", but it is nowhere emmited.

Windows 8
Linux Ubuntu 16.04

**Comment by 50Wliu** [comment]
It's emitted on line 10: https://github.com/atom/keyboard-layout/blob/f98a3306a4f7eeb06002dc25a7b8e19d18783f1f/lib/keyboard-layout.js#L10
